 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function runs a simulated annealing process
% to find the best fit for the model
% It uses the simAnnOpt structure generated by
% generate_sim_ann_options
% WCSTsimAnnVars = WCSTsimAnn(simAnnOpt)

function WCSTsimAnnVars = WCSTsimAnn(simAnnOpt)

%% Print initial time
fprintf('Simulated Annealing WCST\n');
fprintf('Beginning time: %s\n', datestr(now,'HH:MM'));
iter = 1;
discrepancy{1} = [0 0];
delta_discrepancy{1} = 0;

tp = 1;

% Initalise all the variables
initialiseWCST_SA;

% Assign variables from the option structure passed to the function
for par_c = 1:length(simAnnOpt.param_names)
    
    eval(strcat( simAnnOpt.param_names{par_c}, '=', num2str(simAnnOpt.init_values{par_c}) ,';'));
    eval(strcat( 'WCSTsimAnnVars(1).param', num2str(par_c),'=', simAnnOpt.param_names{par_c} ,';'));

end
 
%temperature = start_temperature*(1.5).^(-[1:maxSteps+1]);

while iter <= simAnnOpt.max_steps
     
 fprintf('Iteration %1.0f', iter);
 
 % Random vector: paramter multiplier
 rnp = simAnnOpt.rnd_prop(iter,:); 
 p = unifrnd(0,1); 
   
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 for trial_num = 1:simAnnOpt.max_trials
  initialiseWCST_SA; % Initialise all variables
  
  runWCST;        % Run WCST Simulation
  
  % record performances
  performances_CC(trial_num) = sum(performances.CC);
  performances_TE(trial_num) = performances.TE;
  performances_PE(trial_num) = sum(performances.PE);
  performances_SL3(trial_num) = sum(performances.SL3);
  fprintf('.');
 end
 
 performances_mean.CC = trimmean(performances_CC,10);
 performances_mean.TE = trimmean(performances_TE,10);
 performances_mean.PE = trimmean(performances_PE,10);
 performances_mean.SL3 = trimmean(performances_SL3,10);

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  % Calculate discrepancy with target measures
 
 %discrepancy{iter}(1) = discrepancy_with_penaliser('linnorm',performances_mean.CC, simAnnOpt.CCmean, simAnnOpt.CCstd, 0);
 discrepancy{iter}(1) = discrepancy_with_penaliser('linnorm',performances_mean.TE,simAnnOpt.TEmean, simAnnOpt.TEstd, 0);    
 discrepancy{iter}(2) = discrepancy_with_penaliser('linnorm',performances_mean.PE,simAnnOpt.PEmean, simAnnOpt.PEstd, 0);  
 discrepancy{iter}(3) = discrepancy_with_penaliser('linnorm',performances_mean.SL3, simAnnOpt.SLmean, simAnnOpt.SLstd, 0); 
 
 % Computes discrepancy
 if iter > 1
  delta_discrepancy{iter} = norm(discrepancy{iter}) - norm(discrepancy{iter-1});
 else
  delta_discrepancy{iter} = norm(discrepancy{iter}) - 0;
 end 

 % Register outcome
 WCSTsimAnnVars(iter).CC = performances_mean.CC;
 WCSTsimAnnVars(iter).TE = performances_mean.TE;
 WCSTsimAnnVars(iter).PE = performances_mean.PE;
 WCSTsimAnnVars(iter).SL3 = performances_mean.SL3;
 WCSTsimAnnVars(iter).trials = counter.trial_num - 1;
 
 % Register parameter values
 for par_c = 1:length(simAnnOpt.param_names)
     eval(strcat( 'WCSTsimAnnVars(',num2str(iter),').param', num2str(par_c),'=', simAnnOpt.param_names{par_c} ,';'));
 end
 
 % Register discrepancies
 WCSTsimAnnVars(iter).discrepancy = discrepancy{iter};
 WCSTsimAnnVars(iter).discrepancy_norm = norm(discrepancy{iter});
 WCSTsimAnnVars(iter).discrepancy_mean = mean(discrepancy{iter});
 WCSTsimAnnVars(iter).delta_discrepancy = delta_discrepancy{iter};
 
 % Simulated annealing 
 if delta_discrepancy{iter} < 0  % if there's an improvement
  
  % Move across the parameter space (randomly)
  for par_c = 1:length(simAnnOpt.param_names)
   eval(strcat( simAnnOpt.param_names{par_c}, '=', num2str(rnp(par_c)),'*WCSTsimAnnVars(',num2str(iter),').param', num2str(par_c),';' ));
  end
 else    % if there is no improvement
  if p < exp(- delta_discrepancy{iter}/simAnnOpt.temperature(tp)) || iter <= 1
   fprintf('Annealing...');
   % Move across the parameter space (randomly)
   for par_c = 1:length(simAnnOpt.param_names)
    eval(strcat( simAnnOpt.param_names{par_c}, '=', num2str(rnp(par_c)), '*WCSTsimAnnVars(', num2str(iter),').param', num2str(par_c), ';' ));
   end
  else
   % Move across the parameter space (randomly)
   for par_c = 1:length(simAnnOpt.param_names)
    eval(strcat( simAnnOpt.param_names{par_c}, '=',  num2str(rnp(par_c)), '*WCSTsimAnnVars(',num2str(iter-1),').param', num2str(par_c), ';' ));
   end
  end
  tp = tp + 1;
 end
 
 fprintf('completed. ');
 fprintf('Discrepancy norm: %2.2f', norm(discrepancy{iter}));
 fprintf(' (mean = : %2.2f) \n', mean(discrepancy{iter}));
 
 % Interrupt if discrepancy is small enough
 if norm(discrepancy{iter}) < simAnnOpt.stop_if_discrepancy
  fprintf('...interrupted.');
  beep 
  break;
 end
 
 iter = iter + 1; 
   
end

%% Print results and save

 fprintf('\nSimulated Annealing WCST completed\n');
 fprintf('Ending time: %s\n', datestr(now,'HH:MM'));
 
end


